# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: [push, pull_request]

jobs:
  ubuntu_test:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: cat /etc/os-release
      - run: ls -la
      - run: ls -la ${{ github.workspace }}

  test:
    runs-on: ubuntu-24.04
    container:
      image: golang:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: go test -v

  build:
    runs-on: ubuntu-24.04
    container: golang:latest
    steps:
      - uses: actions/checkout@v4
      - run: go build -v
      - run: ls -la
