name: Go

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04
    container: golang:alpine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: go test -v

  build:
    runs-on: ubuntu-24.04
    container: golang:alpine
    steps:
      - uses: actions/checkout@v4
      - run: go build
      - uses: actions/upload-artifact@v4
        with:
          name: mdtoc
          path: mdtoc
          overwrite: true
