name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version number'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04
    container: golang:alpine
    steps:
      - uses: actions/checkout@v4
      - run: go build
      - uses: actions/upload-artifact@v4
        with:
          name: mdtoc
          path: mdtoc
          overwrite: true
      - run: "echo inputs.version: ${{ inputs.version }}"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          name: "${{ inputs.version }}"
          tag_name: "${{ inputs.version }}"
          files: mdtoc
