name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version number'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04
    container: golang:alpine
    steps:
      - uses: actions/checkout@v4
      - run: go build
      - uses: actions/upload-artifact@v4
        with:
          name: mdtoc
          path: mdtoc
          overwrite: true
      - run: "echo inputs.version: ${{ inputs.version }}"

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.version }}
          release_name: Release ${{ inputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./mdtoc
          asset_name: mdtoc
          asset_content_type: application/zip
