name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-24.04
    container: golang:alpine
    steps:
      - uses: actions/checkout@v4
      - run: go build
      - run: "echo 'TODO: upload build to releases'"
