name: "Unit Tests"

on: [push]

# Unit tests on alpine will not work anymore due to musl having FILE* const.

jobs:
  test_on_archlinux:
    runs-on: ubuntu-24.04
    container: ghcr.io/bfoersterling/cdevel_archlinux:latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4
      - run: make test
